services:
  postgres:
    image: postgres:16-alpine
    container_name: deepsea-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
    ports:
      - '5435:5432'
    volumes:
      - deepsea-postgres-data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - deepsea-network

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: deepsea-auth-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${AUTH_DATABASE_URL}
      PORT: ${AUTH_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    networks:
      - deepsea-network

  observation-service:
    build:
      context: .
      dockerfile: services/observation-service/Dockerfile
    container_name: deepsea-observation-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # URL utilis√©e par Prisma dans observation-service
      DATABASE_URL: ${OBSERVATION_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      OBSERVATION_SERVICE_PORT: ${OBSERVATION_PORT}
      AUTH_SERVICE_URL: ${OBSERVATION_AUTH_SERVICE_URL}
    depends_on:
      - postgres
    ports:
      - '4002:4002'
    networks:
      - deepsea-network

  taxonomy-service:
    build:
      context: .
      dockerfile: services/taxonomy-service/Dockerfile
    container_name: deepsea-taxonomy-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TAXONOMY_SERVICE_PORT: ${TAXONOMY_PORT}
      OBSERVATION_SERVICE_URL: ${TAXONOMY_OBSERVATION_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - observation-service
    ports:
      - '4003:4003'
    networks:
      - deepsea-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: deepsea-gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: ${GATEWAY_PORT}
      AUTH_SERVICE_URL: ${GATEWAY_AUTH_SERVICE_URL}
      OBSERVATION_SERVICE_URL: ${GATEWAY_OBSERVATION_SERVICE_URL}
      TAXONOMY_SERVICE_URL: ${GATEWAY_TAXONOMY_SERVICE_URL}
    ports:
      - '4000:4000'
    depends_on:
      - auth-service
      - observation-service
      - taxonomy-service
    networks:
      - deepsea-network

networks:
  deepsea-network:
    driver: bridge

volumes:
  deepsea-postgres-data:
    driver: local
