services:
  postgres:
    image: postgres:16-alpine
    container_name: deepsea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: deepsea
      POSTGRES_PASSWORD: deepsea
      POSTGRES_DB: deepsea
    ports:
      - '5435:5432'
    volumes:
      - deepsea-postgres-data:/var/lib/postgresql/data
      - ./docker/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - deepsea-network

  auth-service:
    build:
      context: ..
      dockerfile: services/auth-service/Dockerfile
    container_name: deepsea-auth-service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://deepsea:deepsea@postgres:5432/deepsea?schema=auth
      PORT: 3001
      JWT_SECRET: super-secret-change-me
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    networks:
      - deepsea-network

  observation-service:
    build:
      context: ..
      dockerfile: services/observation-service/Dockerfile
    container_name: deepsea-observation-service
    restart: unless-stopped
    environment:
      # URL utilis√©e par Prisma dans observation-service
      DATABASE_URL: postgresql://deepsea:deepsea@postgres:5432/deepsea?schema=public
      JWT_SECRET: super-secret-change-me
      OBSERVATION_SERVICE_PORT: 4002
    depends_on:
      - postgres
    ports:
      - '4002:4002'
    networks:
      - deepsea-network

  taxonomy-service:
    build:
      context: ..
      dockerfile: services/taxonomy-service/Dockerfile
    container_name: deepsea-taxonomy-service
    restart: unless-stopped
    environment:
      TAXONOMY_SERVICE_PORT: 4003
      OBSERVATION_SERVICE_URL: http://observation-service:4002
    depends_on:
      - observation-service
    ports:
      - '4003:4003'
    networks:
      - deepsea-network

networks:
  deepsea-network:
    driver: bridge

volumes:
  deepsea-postgres-data:
    driver: local
