version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: deepsea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: deepsea
      POSTGRES_PASSWORD: deepsea
      POSTGRES_DB: deepsea
    ports:
      - '5435:5432'
    volumes:
      - deepsea-postgres-data:/var/lib/postgresql/data
    networks:
      - deepsea-network

  # Optionnel : interface d’admin pour PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: deepsea-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@deepsea.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - deepsea-network

  observation-service:
    build:
      context: ..
      dockerfile: services/observation-service/Dockerfile
    container_name: deepsea-observation-service
    restart: unless-stopped
    environment:
      # URL utilisée par Prisma dans observation-service
      DATABASE_URL: postgresql://deepsea:deepsea@postgres:5432/deepsea?schema=public
      JWT_SECRET: super-secret-change-me
      OBSERVATION_SERVICE_PORT: 4002
    depends_on:
      - postgres
    ports:
      - '4002:4002'
    networks:
      - deepsea-network

  taxonomy-service:
    build:
      context: ..
      dockerfile: services/taxonomy-service/Dockerfile
    container_name: deepsea-taxonomy-service
    restart: unless-stopped
    environment:
      TAXONOMY_SERVICE_PORT: 4003
      OBSERVATION_SERVICE_URL: http://observation-service:4002
    depends_on:
      - observation-service
    ports:
      - '4003:4003'
    networks:
      - deepsea-network

networks:
  deepsea-network:
    driver: bridge

volumes:
  deepsea-postgres-data:
    driver: local
