services:
  postgres:
    image: postgres:16-alpine
    container_name: deepsea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: deepsea
      POSTGRES_PASSWORD: deepsea
    volumes:
      - deepsea-postgres-data:/var/lib/postgresql/data
      - ./docker/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    ports:
      - "5432:5432"
    networks:
      - deepsea-network

  # observation-service:
  #   build: ../services/observation-service
  #   container_name: deepsea-observation-service
  #   restart: unless-stopped
  #   environment:
  #     # URL utilisée par Prisma dans observation-service
  #     DATABASE_URL: postgresql://deepsea:deepsea@postgres:5432/deepsea-observation?schema=public
  #     JWT_SECRET: super-secret-change-me
  #     OBSERVATION_SERVICE_PORT: 4002
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '4002:4002'
  #   networks:
  #     - deepsea-network

  # auth-service:
  #   build: ../services/auth-service
  #   container_name: deepsea-auth-service
  #   restart: unless-stopped
  #   environment:
  #     # URL utilisée par Prisma dans observation-service
  #     DATABASE_URL: postgresql://deepsea:deepsea@postgres:5432/deepsea-auth?schema=public
  #     JWT_SECRET: super-secret-change-me
  #     OBSERVATION_SERVICE_PORT: 4003
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '4003:4003'
  #   networks:
  #     - deepsea-network

networks:
  deepsea-network:
    driver: bridge

volumes:
  deepsea-postgres-data:
    driver: local
